name: percent_indicator
description: Library that allows you to display progress widgets based on percentage, can be Circular or Linear, you can also customize it to your needs.
version: 2.1.1
author: Diego Velásquez <diegoveloper@gmail.com>
homepage: https://twitter.com/diegoveloper
repository: https://github.com/aeyrium/bezier-chart

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
